### ISSUE TITLE
EN LA BETA NO FUNCIONA LO SIGUIENTE

### ISSUE THREAD

**Issue by luisjariego** [davidnevadoc/PPROG#2]
En la beta, si eliminamos el player del archivo de texto de donde se cargan los datos, el juego da violación de segmento, no funciona, y sí debería (en el alpha va). Será por algo del cop... no lo he encontrado.

**Comment by davidnevadoc** [comment]
que es lo que tiene la beta que no tenga la alpha?

**Comment by luisjariego** [comment]
Básicamente el cop

**Comment by luisjariego** [comment]
Arreglao by me.
