### ISSUE TITLE
Mapas

### ISSUE THREAD

**Issue by davidnevadoc** [davidnevadoc/PPROG#6]
Creo que los mapas se quedan demasiado vacios, al ser tan grandes y los objetos y personas ocupar  un solo caracter se quedan bastante vacios (y cutres). Tendriamos que mirar lo del color tambien.

**Comment by luisjariego** [comment]
Pues se rellenan más. Yo creo que cambiar ahora el tamaño mejor no. Del color dijimos que pasábamos, es una movida, tardaríamos la vida.

**Comment by davidnevadoc** [comment]
Si pudiesemos poner que los objetos  fuesen mas de un caracter estaria de puta  madre pero supongo que es una movida que flipas
